// src/lib/components/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    variant = 'primary',
    size = 'md',
    href,
    disabled = false,
    type = 'button',
    onclick,
    class: className = '',
    children
  }: {
    variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
    size?: 'sm' | 'md' | 'lg';
    href?: string;
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    onclick?: (e: MouseEvent) => void;
    class?: string;
    children?: Snippet;
  } = $props();

  const baseStyles = 'inline-flex items-center justify-center font-body font-medium rounded-[10px] leading-tight transition-all duration-200 cursor-pointer select-none active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none';
  
  const variants = {
    primary: 'bg-gradient-to-br from-brand-from to-brand-to text-white shadow-cta shadow-[inset_0_1.5px_3px_rgba(255,255,255,0.35),_inset_0_-1.5px_3px_rgba(0,0,0,0.2)] hover:shadow-[0_6px_24px_rgba(232,89,60,0.45)] hover:-translate-y-0.5 border border-brand-from/20',
    secondary: 'bg-surface text-text-primary border border-border-custom shadow-card hover:shadow-card-hover hover:-translate-y-0.5',
    outline: 'bg-transparent text-text-primary border-2 border-text-primary/12 dark:border-text-primary/18 hover:border-brand-from/80 hover:text-brand-from hover:bg-brand-from/[0.03] shadow-sm',
    ghost: 'bg-transparent text-text-secondary hover:text-text-primary hover:bg-surface-3'
  };

  const sizes = {
    sm: 'px-3 py-1 text-[11px]',
    md: 'px-4 py-1.5 text-xs sm:text-sm',
    lg: 'px-5.5 py-2 text-sm sm:text-base'
  };
</script>

{#if href}
  <a
    {href}
    class="{baseStyles} {variants[variant]} {sizes[size]} {className}"
  >
    {#if children}
      {@render children()}
    {/if}
  </a>
{:else}
  <button
    {type}
    {disabled}
    {onclick}
    class="{baseStyles} {variants[variant]} {sizes[size]} {className}"
  >
    {#if children}
      {@render children()}
    {/if}
  </button>
{/if}

// components/ui/button.tsx
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-md border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all duration-200 ease-out outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        // The signature orange gradient CTA with a soft glow (see .btn-gradient).
        default: "btn-gradient",
        // White button + soft hairline outline, on the cream canvas.
        outline:
          "border-border bg-card text-ink shadow-xs hover:border-primary/30 hover:bg-secondary-bg aria-expanded:bg-secondary-bg dark:border-input dark:bg-input/20 dark:text-on-dark dark:hover:bg-input/40",
        secondary:
          "bg-secondary-bg text-ink hover:bg-surface-cream-strong aria-expanded:bg-surface-cream-strong",
        // Secondary used over dark surfaces — stays dark, never inverts.
        "on-dark":
          "bg-surface-dark-elevated text-on-dark hover:bg-[color-mix(in_oklab,var(--color-surface-dark-elevated),#fff_8%)]",
        // Inverted (white) button that sits inside a full-bleed orange band.
        "on-coral": "bg-white text-primary hover:bg-white/90",
        ghost:
          "text-ink hover:bg-secondary-bg aria-expanded:bg-secondary-bg dark:text-on-dark dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-10 gap-1.5 px-5 has-data-[icon=inline-end]:pr-4 has-data-[icon=inline-start]:pl-4",
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),10px)] px-2 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-8 gap-1 px-3.5 text-[0.8rem] has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-11 gap-2 px-6 text-[0.95rem] has-data-[icon=inline-end]:pr-5 has-data-[icon=inline-start]:pl-5",
        icon: "size-9",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-7 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
